server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apus_demo
    username: root
    password: Vl121620.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true


openapi:
  service:
    api-docs: API-Service document dev
    description: API service of Booking Cinema dev
    server: http://localhost:${server.port}
    title: ${API_TITLE:DUMMY-API-TITLE}
    version: 1.0.0

client:
  resources-service:
    url: https://resources-service.dev.apusplatform.com
    path: /api/v1
  product-manufactor-service:
    url: https://product-manufactor-service.dev.apusplatform.com
    path: /api/v1
